//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactsApi.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact was not found..
        /// </summary>
        public static string ContactNotFound {
            get {
                return ResourceManager.GetString("ContactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact was removed..
        /// </summary>
        public static string ContactRemoved {
            get {
                return ResourceManager.GetString("ContactRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact skill was created..
        /// </summary>
        public static string ContactSkillCreated {
            get {
                return ResourceManager.GetString("ContactSkillCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact skill already exists..
        /// </summary>
        public static string ContactSkillExists {
            get {
                return ResourceManager.GetString("ContactSkillExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact skill was not found..
        /// </summary>
        public static string ContactSkillNotFound {
            get {
                return ResourceManager.GetString("ContactSkillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact skill was updated..
        /// </summary>
        public static string ContactSkillUpdated {
            get {
                return ResourceManager.GetString("ContactSkillUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact was updated..
        /// </summary>
        public static string ContactUpdated {
            get {
                return ResourceManager.GetString("ContactUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill level was not found..
        /// </summary>
        public static string SkillLevelNotFound {
            get {
                return ResourceManager.GetString("SkillLevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill was not found..
        /// </summary>
        public static string SkillNotFound {
            get {
                return ResourceManager.GetString("SkillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill was removed..
        /// </summary>
        public static string SkillRemoved {
            get {
                return ResourceManager.GetString("SkillRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill was updated..
        /// </summary>
        public static string SkillUpdated {
            get {
                return ResourceManager.GetString("SkillUpdated", resourceCulture);
            }
        }
    }
}
